merging the elements of the contact page
WildCodeSchool/p3-g1-sept21-lille-reactJs-ophtalmology-frontend pull request #10
Opened 2021-12-21 15:45 UTC by Vjerem

2021-12-21 15:57 UTC, KeerhemFR requested changes

2021-12-21 15:57 UTC, KeerhemFR commented on src/App.jsx
> +import Contact from './components/Contact';
Must be above, the css sheets arrive after the components

2021-12-21 15:57 UTC, KeerhemFR commented on src/components/Contact/index.jsx
> +import SContact from './SContact';
Style sheets must come after components

2021-12-21 15:57 UTC, KeerhemFR commented on src/components/Contact/SContact.jsx
> +  & & <* {
Don't understand that part, need some explanations

2021-12-21 16:07 UTC, KeerhemFR approved these changes
See no evil here

2021-12-22 08:32 UTC, Hacene010 approved these changes

2021-12-22 08:54 UTC, merged