Contact
WildCodeSchool/p3-g1-sept21-lille-reactJs-ophtalmology-frontend pull request #15
Opened 2022-01-04 16:50 UTC by Vjerem

mobile version of contact page

2022-01-05 08:42 UTC, KeerhemFR requested changes
Saw one little evil, fix it and it should be good

2022-01-05 08:42 UTC, KeerhemFR commented on src/components/Contact/ContactInfo/style.jsx
> +      width: 10vh;
have to use vw for width instead of vh

2022-01-05 08:59 UTC, KeerhemFR approved these changes, later dismissed
See no evil, but will have to be careful with vw and vh and see how it render. Maybe be subject to some modification later depending the outcome.

2022-01-05 14:53 UTC, Hacene010 requested changes
plz check the empty lines. Your line breaks must be consistent throughout the project

2022-01-05 14:53 UTC, Hacene010 commented on src/components/Contact/ContactInfo/style.jsx
> +
empty line !!!

2022-01-05 14:53 UTC, Hacene010 commented on src/components/Contact/ContactInfo/style.jsx
empty line

2022-01-05 15:58 UTC, KeerhemFR approved these changes
See no evil

2022-01-06 13:06 UTC, Hacene010 approved these changes

2022-01-06 14:04 UTC, merged