Commit message was too long, see desc 👇
WildCodeSchool/p3-g1-sept21-lille-reactJs-ophtalmology-frontend pull request #18
Opened 2022-01-05 14:53 UTC by Agent-Roman-Off

Created the introduction component for the home page with a link to a more detailed introduction page also created here. Created the links on the App.jsx file.

2022-01-05 15:05 UTC, KeerhemFR approved these changes
Some fix are required.

2022-01-05 15:05 UTC, KeerhemFR commented on src/components/About/style.jsx
> +const SAbout = styled.body`
body is already in index.html, should use something else

2022-01-05 15:05 UTC, KeerhemFR commented on src/components/Home/Introduction/style.jsx
> +    flex-flow: column;
why flex-flow if only using direction? add a wrap or no-wrap value in the flex-flow, or change it to a simple flex-direction

2022-01-05 15:05 UTC, KeerhemFR commented on src/components/Home/Introduction/style.jsx
> +    flex-flow: column;
same

2022-01-05 15:05 UTC, KeerhemFR commented on src/components/Home/Introduction/style.jsx
> +      flex-flow: row;
same

2022-01-05 15:05 UTC, KeerhemFR commented on src/components/Home/index.jsx
> +    </body>
body already in index.html, should be something else

2022-01-05 15:05 UTC, KeerhemFR commented on src/components/Home/style.jsx
> +  body {
same

2022-01-05 15:05 UTC, KeerhemFR commented on src/components/Home/style.jsx
> +    body {
same

2022-01-05 15:05 UTC, KeerhemFR requested changes
Some fix are required

2022-01-05 15:27 UTC, KeerhemFR approved these changes
See no evil

2022-01-06 13:02 UTC, Hacene010 approved these changes

2022-01-06 14:04 UTC, merged