I created a component Picture and i put this in dropdownWindows.
WildCodeSchool/p3-g1-sept21-lille-reactJs-ophtalmology-frontend pull request #31
Opened 2022-01-24 14:43 UTC by Sonya092

2022-01-24 16:00 UTC, KeerhemFR requested changes
Just need a change on the alt and will be good for me

2022-01-24 16:00 UTC, KeerhemFR commented on src/components/Picture/index.jsx
> +        return <img src={picture.url} alt="opthalmology" />;
The alt has to be {picture.description} so the alt match the image content

2022-01-25 07:58 UTC, KeerhemFR requested changes

2022-01-25 07:58 UTC, KeerhemFR commented on src/components/Picture/index.jsx
> +        return <img src={picture.description} alt="opthalmology" />;
You didn't read the message well : the src was good with {picture.url} . What needed to be change was the alt, with {picture.description}

2022-01-25 09:02 UTC, KeerhemFR approved these changes

2022-01-25 09:12 UTC, Hacene010 approved these changes

2022-01-25 09:12 UTC, Hacene010 commented on src/components/Picture/index.jsx
> +    axios.get(`http://localhost:5050/images`).then(({ data }) => {
Don't forget to hide your url intro a .env file

2022-01-25 11:22 UTC, merged