add contact info and css
WildCodeSchool/p3-g1-sept21-lille-reactJs-ophtalmology-frontend pull request #8
Opened 2021-12-17 10:34 UTC by Vjerem

2021-12-17 10:50 UTC, KeerhemFR requested changes
Be careful to delete the comments before making a PR, and to repetition in code when no necessary

2021-12-17 10:50 UTC, KeerhemFR commented on src/components/Contact/ContactInfo/SContactInfo.jsx
> +      width: 3vw;
Size will change depending the screen size and some evil may appears

2021-12-17 10:50 UTC, KeerhemFR commented on src/components/Contact/ContactInfo/SContactInfo.jsx
> +      /*border: 5px solid orange;*/
/!\ Remove the comments /!\

2021-12-17 10:50 UTC, KeerhemFR commented on src/components/Contact/ContactInfo/SContactInfo.jsx
> +      display: flex;
Already in display flex from the start, no need to write it again here since it doesn't change

2021-12-17 10:50 UTC, KeerhemFR commented on src/components/Contact/ContactInfo/SContactInfo.jsx
> +      width 3vw
Same as display flex : if the parameter doesn't change, no need to write it again

2021-12-17 10:50 UTC, KeerhemFR commented on src/components/Contact/ContactInfo/index.jsx
> +          src="https://img.icons8.com/ios-filled/100/000000/address--v1.png"
change the /000000/ in url to /ffffff/ to have a white icon in the box

2021-12-17 10:50 UTC, KeerhemFR commented on src/components/Contact/ContactInfo/index.jsx
> +          src="https://img.icons8.com/ios-filled/100/000000/email.png"
Same

2021-12-17 10:50 UTC, KeerhemFR commented on src/components/Contact/ContactInfo/index.jsx
> +          src="https://img.icons8.com/ios-filled/100/000000/phone.png"
Same

2021-12-17 11:08 UTC, Agent-Roman-Off submitted a review, later dismissed
doesn't look like there's any evil remaining, but there's still a conflict that must be resolved (im gonna look into it)

2021-12-17 14:37 UTC, KeerhemFR approved these changes, later dismissed
See no evil here

2021-12-17 14:37 UTC, KeerhemFR commented on src/App.jsx
> +  return <ContactInfos />;
Please do not leave component for test in App, it will make conflicts

2021-12-17 14:38 UTC, KeerhemFR approved these changes, later dismissed
Still not seeing evil after erasing the conflict

2021-12-17 16:40 UTC, Hacene010 requested changes
Seen one evil.

2021-12-17 16:40 UTC, Hacene010 commented on src/components/Contact/ContactInfo/SContactInfo.jsx
> +    box-shadow: inset -1px 3px 8px 5px #1f87ff, 2px 5px 16px 0px #0b325e,
Plz remove this line

2021-12-21 08:55 UTC, KeerhemFR approved these changes
See no evil

2021-12-21 09:08 UTC, Hacene010 approved these changes

2021-12-21 09:19 UTC, merged